const aula1 = {
    id: "aula1", title: "Módulo 1: Arquitetura Física (DDL)", theme: "ddl",
    teoria: {
        desafio: "<strong>Situação-Problema:</strong> Você acaba de ser contratado como Desenvolvedor Júnior na EdTech 'FutureTech'. No seu primeiro dia, o Tech Lead joga um Diagrama Entidade-Relacionamento (DER) impresso na sua mesa e diz: <em>'A nova API em Node.js está pronta, mas não temos onde salvar os dados. Sua Sprint 1 é erguer a fundação física desse banco no servidor de Produção.'</em><br><br><strong>Pergunta Norteadora:</strong> Como garantimos que o sistema impeça um usuário de matricular um aluno em um Curso que não existe? (Dica: Na arquitetura relacional, Tabelas 'Pais' nascem antes das tabelas 'Filhas'. Aprenda isso na dor!).",
        clil: [
            { term: "CREATE", desc: "Criar. O verbo fundacional. Constrói algo novo a partir do zero absoluto no disco da nuvem." },
            { term: "ALTER", desc: "Alterar. Modifica as paredes de uma estrutura já existente que está com a aplicação em pleno voo." },
            { term: "DROP", desc: "Derrubar. O botão vermelho. Destrói completamente o arquivo estrutural e pulveriza os dados juntos." },
            { term: "PRIMARY KEY (PK) / FOREIGN KEY (FK)", desc: "A Identidade Única inflexível (PK) e o Vínculo Relacional de Integridade (FK)." }
        ]
    },
    praticaSetup: null,
    pratica: [
        { 
            title: "Passo 0: A Sandbox de Testes", 
            desc: "Um Dev Júnior nunca testa scripts na base de produção da empresa. Sempre crie um ambiente seguro (Sandbox) antes de brincar com DDL. Crie o terreno lógico e aponte o cursor do sistema para dentro dele.", 
            codes: [
                { label: "SQL Server + MySQL", content: `CREATE DATABASE GestaoEscolar_Lab;\nGO\n\n-- Aponta o radar do motor SQL para dentro da Sandbox criada\nUSE GestaoEscolar_Lab;\nGO` },
                { label: "PostgreSQL", content: `CREATE DATABASE GestaoEscolar_Lab;\n\n-- No terminal PSQL, você conecta fisicamente ao banco assim:\n\\c GestaoEscolar_Lab;` },
                { label: "Oracle", content: `-- No Oracle Corporativo, a abordagem é criar um Schema atrelado fisicamente a um User (Dono).\nCREATE USER GestaoEscolar_Lab IDENTIFIED BY SenhaSegura123;\nGRANT DBA TO GestaoEscolar_Lab;\nALTER SESSION SET CURRENT_SCHEMA = GestaoEscolar_Lab;` }
            ]
        },
        { 
            title: "Passo 1: A Armadilha da Ordem (O Erro Didático)", 
            desc: "A pressa é inimiga da arquitetura. Tente criar uma tabela Filha (TURMA) que depende intimamente de um Curso, ANTES da tabela Curso existir fisicamente no disco. Veja o motor do banco barrar a sua ação para proteger a aplicação de gerar dados órfãos.", 
            codes: [
                { label: "Aviso: Erro de Compilação DDL", content: `-- TENTATIVA FRUSTRADA: O banco varrerá o disco e não achará a tabela 'CURSO' para amarrar a Foreign Key.\nCREATE TABLE TURMA (\n    id INT PRIMARY KEY,\n    curso_id INT NOT NULL,\n    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (curso_id) REFERENCES CURSO(id)\n);\n\n-- RESULTADO NO CONSOLE DO SERVIDOR (Crash):\n-- "Foreign key 'FK_TURMA_CURSO' references invalid table 'CURSO'."` }
            ]
        },
        { 
            title: "Passo 2: Construindo as Entidades Fortes (Pais)", 
            desc: "Você aprendeu a lição. A forma correta é criar primeiro as entidades independentes, que não possuem amarras (sem FKs). Elas são os alicerces. Repare atentamente na diferença brutal de sintaxe nas chaves auto-incrementais dependendo da empresa do seu SGBD.", 
            codes: [
                { label: "SQL Server", content: `CREATE TABLE ALUNO (\n    id INT IDENTITY(1,1) PRIMARY KEY,\n    matricula NVARCHAR(20) UNIQUE NOT NULL,\n    nome NVARCHAR(100) NOT NULL,\n    data_nascimento DATE NOT NULL\n);\n\nCREATE TABLE DOCENTE (\n    id INT IDENTITY(1,1) PRIMARY KEY,\n    registro NVARCHAR(20) UNIQUE NOT NULL,\n    nome NVARCHAR(100) NOT NULL,\n    especialidade NVARCHAR(100) NOT NULL\n);\n\nCREATE TABLE CURSO (\n    id INT IDENTITY(1,1) PRIMARY KEY,\n    nome NVARCHAR(100) NOT NULL,\n    descricao NVARCHAR(MAX) NULL,\n    carga_horaria INT NOT NULL\n);` },
                { label: "PostgreSQL", content: `CREATE TABLE ALUNO (\n    id SERIAL PRIMARY KEY,\n    matricula VARCHAR(20) UNIQUE NOT NULL,\n    nome VARCHAR(100) NOT NULL,\n    data_nascimento DATE NOT NULL\n);\n\nCREATE TABLE DOCENTE (\n    id SERIAL PRIMARY KEY,\n    registro VARCHAR(20) UNIQUE NOT NULL,\n    nome VARCHAR(100) NOT NULL,\n    especialidade VARCHAR(100) NOT NULL\n);\n\nCREATE TABLE CURSO (\n    id SERIAL PRIMARY KEY,\n    nome VARCHAR(100) NOT NULL,\n    descricao TEXT NULL,\n    carga_horaria INT NOT NULL\n);` },
                { label: "MySQL", content: `CREATE TABLE ALUNO (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    matricula VARCHAR(20) UNIQUE NOT NULL,\n    nome VARCHAR(100) NOT NULL,\n    data_nascimento DATE NOT NULL\n);\n\nCREATE TABLE DOCENTE (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    registro VARCHAR(20) UNIQUE NOT NULL,\n    nome VARCHAR(100) NOT NULL,\n    especialidade VARCHAR(100) NOT NULL\n);\n\nCREATE TABLE CURSO (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    nome VARCHAR(100) NOT NULL,\n    descricao TEXT NULL,\n    carga_horaria INT NOT NULL\n);` },
                { label: "Oracle", content: `CREATE TABLE ALUNO (\n    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n    matricula VARCHAR2(20) UNIQUE NOT NULL,\n    nome VARCHAR2(100) NOT NULL,\n    data_nascimento DATE NOT NULL\n);\n\nCREATE TABLE DOCENTE (\n    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n    registro VARCHAR2(20) UNIQUE NOT NULL,\n    nome VARCHAR2(100) NOT NULL,\n    especialidade VARCHAR2(100) NOT NULL\n);\n\nCREATE TABLE CURSO (\n    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n    nome VARCHAR2(100) NOT NULL,\n    descricao CLOB NULL,\n    carga_horaria NUMBER NOT NULL\n);` }
            ]
        },
        { 
            title: "Passo 3: As Entidades Dependentes (Filhas e Associativas)", 
            desc: "Com o terreno preparado, amarramos as filhas usando as Constraints. A tabela associativa ALUNO_TURMA possui uma Chave Primária Composta (A união de duas FKs) que garante que o mesmo aluno não seja matriculado duas vezes na mesmíssima turma acidentalmente.", 
            codes: [
                { label: "SQL Server", content: `CREATE TABLE TURMA (\n    id INT IDENTITY(1,1) PRIMARY KEY,\n    ano_semestre NVARCHAR(10) NOT NULL,\n    curso_id INT NOT NULL,\n    docente_id INT NOT NULL,\n    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (curso_id) REFERENCES CURSO(id),\n    CONSTRAINT FK_TURMA_DOCENTE FOREIGN KEY (docente_id) REFERENCES DOCENTE(id)\n);\n\nCREATE TABLE ALUNO_TURMA (\n    aluno_id INT NOT NULL,\n    turma_id INT NOT NULL,\n    data_matricula DATE DEFAULT GETDATE(),\n    nota DECIMAL(5,2) NULL, \n    faltas INT DEFAULT 0,\n    CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (aluno_id, turma_id),\n    CONSTRAINT FK_ALUNO_TURMA_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNO(id),\n    CONSTRAINT FK_ALUNO_TURMA_TURMA FOREIGN KEY (turma_id) REFERENCES TURMA(id)\n);` },
                { label: "PostgreSQL + MySQL", content: `CREATE TABLE TURMA (\n    id SERIAL PRIMARY KEY, /* MySQL: INT AUTO_INCREMENT */\n    ano_semestre VARCHAR(10) NOT NULL,\n    curso_id INT NOT NULL,\n    docente_id INT NOT NULL,\n    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (curso_id) REFERENCES CURSO(id),\n    CONSTRAINT FK_TURMA_DOCENTE FOREIGN KEY (docente_id) REFERENCES DOCENTE(id)\n);\n\nCREATE TABLE ALUNO_TURMA (\n    aluno_id INT NOT NULL,\n    turma_id INT NOT NULL,\n    data_matricula DATE DEFAULT CURRENT_DATE,\n    nota DECIMAL(5,2) NULL, \n    faltas INT DEFAULT 0,\n    CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (aluno_id, turma_id),\n    CONSTRAINT FK_ALUNO_TURMA_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNO(id),\n    CONSTRAINT FK_ALUNO_TURMA_TURMA FOREIGN KEY (turma_id) REFERENCES TURMA(id)\n);` },
                { label: "Oracle", content: `CREATE TABLE TURMA (\n    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n    ano_semestre VARCHAR2(10) NOT NULL,\n    curso_id NUMBER NOT NULL,\n    docente_id NUMBER NOT NULL,\n    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (curso_id) REFERENCES CURSO(id),\n    CONSTRAINT FK_TURMA_DOCENTE FOREIGN KEY (docente_id) REFERENCES DOCENTE(id)\n);\n\nCREATE TABLE ALUNO_TURMA (\n    aluno_id NUMBER NOT NULL,\n    turma_id NUMBER NOT NULL,\n    data_matricula DATE DEFAULT SYSDATE,\n    nota NUMBER(5,2) NULL, \n    faltas NUMBER DEFAULT 0,\n    CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (aluno_id, turma_id),\n    CONSTRAINT FK_ALUNO_TURMA_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNO(id),\n    CONSTRAINT FK_ALUNO_TURMA_TURMA FOREIGN KEY (turma_id) REFERENCES TURMA(id)\n);` }
            ]
        }
    ],
    retro: [
        { q: "Por que somos obrigados a criar as tabelas Pais antes das Filhas?", a: "A Tabela Turma (Filha) possui chaves estrangeiras (FK) que apontam explicitamente para Curso e Docente (Pais). O motor do banco de dados atua como um juiz rigoroso verificando a existência do destino em tempo real. Ele dará um erro fatal (como testamos no Passo 1) e bloqueará a criação se o Curso não estiver salvo previamente no disco." },
        { q: "Qual a diferença técnica entre os comandos DROP e DELETE?", a: "O DROP é um comando estrutural (DDL) de alto risco cibernético: ele apaga o arquivo físico da tabela do disco rígido, destruindo as colunas, o projeto do arquiteto e os dados juntos. O DELETE é manipulação rotineira (DML): ele apaga apenas as linhas de texto preenchidas, mantendo a estrutura das paredes da tabela intacta, em pé e vazia." },
        { q: "Para que serve o termo restritivo CONSTRAINT?", a: "Ele serve puramente para o DBA 'batizar' a regra de negócio do software com um nome explícito (ex: FK_TURMA_CURSO). Sem ela, o banco cria um hash criptografado aleatório. Se a aplicação tentar fazer uma inserção inválida (matricular aluno num curso fantasma), o log de erro mostrará o nome que você deu, facilitando muito o troubleshooting do programador Backend." }
    ],
    quiz: [
        { q: "Qual linguagem (subconjunto SQL) utilizamos para criar, alterar e destruir estruturas lógicas e físicas no servidor?", opts: [ {t:"DML", c:false}, {t:"DDL", c:true}, {t:"DCL", c:false} ] },
        { q: "O que o comando estrutural IDENTITY(1,1) faz especificamente no ecossistema SQL Server?", opts: [ {t:"Garante que a string seja única.", c:false}, {t:"Converte automaticamente a coluna em uma Chave Estrangeira.", c:false}, {t:"Gera o ID matematicamente de forma automática no kernel, somando 1 a cada novo registro inserido.", c:true} ] },
        { q: "Em quais cenários arquiteturais de negócios aplicamos ativamente os tipos de dados VARCHAR ou NVARCHAR?", opts: [ {t:"Em colunas transacionais financeiras.", c:false}, {t:"Em colunas que armazenarão letras, textos ou strings de tamanho variante na aplicação.", c:true}, {t:"Em campos binários numéricos.", c:false} ] },
        { q: "Por qual motivo tático um DBA aplica a restrição de software NOT NULL na coluna 'Nome'?", opts: [ {t:"Para permitir cadastros anônimos ágeis.", c:false}, {t:"Para proteger e blindar a base, forçando o motor a rejeitar com erro HTTP qualquer tentativa da API Web que venha com texto vazio.", c:true}, {t:"Para criptografar com Hash a senha enviada.", c:false} ] },
        { q: "Qual comando letal DDL destrói a tabela inteira, o projeto e toda a sua estrutura física de um disco da nuvem AWS?", opts: [ {t:"DROP TABLE", c:true}, {t:"DELETE TABLE", c:false}, {t:"TRUNCATE TABLE", c:false} ] },
        { q: "Na teoria de Codd e Bancos Relacionais, o que define intrinsecamente uma Primary Key (PK)?", opts: [ {t:"Um indexador de regra de ordenação ascendente.", c:false}, {t:"Uma ponte de conexão aberta cloud API.", c:false}, {t:"O identificador numérico/texto único, inalterável e exclusivo designado para cada linha isolada de uma tabela.", c:true} ] },
        { q: "O que define e qual o propósito irrefutável de uma Foreign Key (FK)?", opts: [ {t:"Atua garantindo estritamente a Integridade Referencial do negócio, apontando de forma obrigatória para a PK de outra tabela pai.", c:true}, {t:"É a senha em Hash gerada para o FrontEnd.", c:false}, {t:"A chave de acesso a um endpoint REST.", c:false} ] },
        { q: "A nova lei entrou em vigor hoje! Como adicionar uma nova coluna chamada 'lgpd_aceite' em uma tabela que já está há anos em produção sem perder 1 único cliente da base?", opts: [ {t:"ALTER TABLE ... ADD", c:true}, {t:"CREATE COLUMN IN TABLE", c:false}, {t:"UPDATE TABLE SET COLUMN", c:false} ] },
        { q: "A entidade física intermediária 'ALUNO_TURMA' que nós construímos hoje soluciona e desata qual grave problema de modelagem de cardinalidade?", opts: [ {t:"O problema das heranças múltiplas em orientação a objetos.", c:false}, {t:"A complexidade dos relacionamentos N:M (Muitos para Muitos), quebrando a confusão em duas pontas simples de 1:N.", c:true}, {t:"O cruzamento de relacionamentos redundantes estritos de 1:1.", c:false} ] },
        { q: "Qual a utilidade corporativa prática e funcional de se inserir a regra de DEFAULT GETDATE() na engenharia da 'data_matricula'?", opts: [ {t:"Forçar o front-end a formatar e printar a data no padrão PT-BR.", c:false}, {t:"Caso o código Node.js do desenvolvedor submeta o formulário esquecendo ou omitindo de enviar a data atual do usuário, o próprio núcleo físico do servidor assume a responsabilidade cravando no registro o milissegundo do relógio da máquina.", c:true}, {t:"Bloquear o processador do banco contra cadastros invasivos realizados por bots aos sábados e domingos de madrugada.", c:false} ] }
    ]
};